<?php


/**
*
* NavBar class
*
* Used to add NavBar to unique pages.
*
*
* Usage:
*	<body>
*		$nav = new NavBar();
*      	$nav->setNavSection();
*		$nav->getNav();
*
* @author Zachery Frye <zfrye858@uwsp.edu>
*
*/

class NavBar {
	private $_theNav;
	private $_currURL;
	private $pages = array(
		'home.php' => 'Home',
		'about.php' => 'About',
		'contact.php' => 'Contact',
		'search.php' => 'Search',
	
	);
	
	function __construct($currURL) {
		$this->_currPage = $currURL;
	}
	
	function setNavSection() {
		$returnVal = "";
		$returnVal = "<!--This is Autogenerated by NavBar.php -->\n";
		$returnVal .= "<nav>\n";
		$returnVal .= " <ul>\n";
		foreach($this->pages as $filename => $pageTitle) {
			if($filename == $this->_currPage){
				$returnVal .= "  <li><a href='#' class='active'>$pageTitle</a></li>\n";
			}else{
				$returnVal .= "  <li><a href='$filename'>$pageTitle</a></li>\n";
			}
		}
		$returnVal .= " </ul>\n";
		$returnVal .= "</nav>\n";
		
		$this->_theNav = $returnVal;
	}
	
	function getNav(){
		return $this->_theNav;
	}
}

// http://cnmtsrv2.uwsp.edu/~zfrye858/workingNav/home.php
// https://stackoverflow.com/questions/4908932/dynamic-navigation-in-php